app:
  name: simpleproduct
  role: command
  cluster-name: simple-axon-demo

spring:
  profiles:
    include:
    - web
    - swagger
    - locale
    - logging
    - axon-amqp
    - axon-jgroups
    - axon-eventstore

axon:
  eventstore:
    aggregate-package: com.example.simpleproductcommand.aggregates

