axon:
  distributed:
    jgroups:
      configuration-file: jgroups/udp.xml

server:
  port: 9091

logging:
  level:
    org.axonframework: debug
    com.example: debug

spring:
  rabbitmq:
    host: rabbit-local
  jpa:
      hibernate.ddl-auto: update


