app:
  name: simpleorder
  role: command
  descriptions: 订单命令服务
  datasource:
    username: root
    password: ckVxkqVs5Gr4lSLtJTsa301UJ9TwjHR/empatRoKLhyav2f6YSsti7OmVQfaO7xreYXoIbYPmHo6p11UbY/XJg==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN9dGI7ljLxGCLgm0jzfgaYrzYaIAyhpz3v1KffP5Pvv0nKhJzjD8vbRghFWakv6xHZHPPwjgZtFVb10HiblEHECAwEAAQ==

spring:
  profiles:
    include:
    - web
    - swagger
    - locale
    - logging
    - jpa
    - druid
    - axon-jgroups
    - axon-amqp-producer
    - axon-amqp-consumer
    - axon-eventstore
    - axon-scheduler
    - axon-saga

axon:
  amqp:
    consumer:
      queue: moses-simpleproduct-command
  eventhandling:
    processors:
      queueListener:
        source: queueMessageSource
  eventstore:
    aggregate-class: com.example.simpleordercommand.aggregates.OrderAggregate
  saga:
    saga-class: com.example.simpleordercommand.saga.OrderSaga
  distributed:
    jgroups:
      cluster-name: simple-axon-demo

