axon:
  distributed:
    jgroups:
      configuration-file: jgroups/udp.xml

server:
  port: 9095

logging:
  level:
    org.axonframework: debug
    cn.vpclub.moses: debug

spring:
  rabbitmq:
    host: rabbit-local
  jpa:
    hibernate.ddl-auto: update
