app:
  name: simpleproduct
  role: query
  descriptions: 商品查询服务
  datasource:
    username: root
    password: ckVxkqVs5Gr4lSLtJTsa301UJ9TwjHR/empatRoKLhyav2f6YSsti7OmVQfaO7xreYXoIbYPmHo6p11UbY/XJg==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN9dGI7ljLxGCLgm0jzfgaYrzYaIAyhpz3v1KffP5Pvv0nKhJzjD8vbRghFWakv6xHZHPPwjgZtFVb10HiblEHECAwEAAQ==

spring:
  profiles:
    include:
    - web
    - swagger
    - locale
    - jpa
    - druid
    - axon-amqp-consumer

axon:
  amqp:
    consumer:
      queue: moses-simpleproduct-command
  eventhandling:
    processors:
      product:
        source: productQueueMessageSource