app:
  project: moses
  name: simpleproduct
  role: query
  descriptions: 商品查询服务
  cluster-name: simple-axon-demo
  datasource:
    username: demo
    password: ckVxkqVs5Gr4lSLtJTsa301UJ9TwjHR/empatRoKLhyav2f6YSsti7OmVQfaO7xreYXoIbYPmHo6p11UbY/XJg==
    druid:
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN9dGI7ljLxGCLgm0jzfgaYrzYaIAyhpz3v1KffP5Pvv0nKhJzjD8vbRghFWakv6xHZHPPwjgZtFVb10HiblEHECAwEAAQ==

spring:
  profiles:
    include:
    - web
    - swagger
    - locale
    - jpa
    - druid
    - axon-amqp
